# Generated by Django 6.0.3 on 2026-03-31 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateField()),
                ('date_order', models.IntegerField(default=0)),
                ('thanks', models.CharField(default='', max_length=255)),
                ('url', models.URLField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChumpMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=50)),
                ('media', models.ImageField(upload_to='chumps/media/')),
                ('chump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='chumps.chump')),
            ],
        ),
    ]
