# Generated by Django 6.0.3 on 2026-04-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chumps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chumpmedia',
            name='media_order',
            field=models.IntegerField(default=0),
        ),
    ]
