# Generated by Django 6.0.3 on 2026-04-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chumps', '0002_chumpmedia_media_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('headline', models.CharField(default='', max_length=255)),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('headline', models.CharField(default='', max_length=255)),
                ('text', models.TextField(default='')),
                ('background_color', models.CharField(default='#4a6da7', max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='chumpmedia',
            name='media',
            field=models.ImageField(upload_to='chumps/'),
        ),
    ]
