# Generated by Django 6.0.3 on 2026-04-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chumps', '0003_era_specialevent_alter_chumpmedia_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialevent',
            name='text',
        ),
    ]
