# Generated by Django 6.0.3 on 2026-04-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chumps', '0004_remove_specialevent_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='era',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='specialevent',
            name='headline',
        ),
        migrations.AddField(
            model_name='specialevent',
            name='text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='era',
            name='text',
            field=models.TextField(default='', max_length=255),
        ),
    ]
