# Generated by Django 6.0.3 on 2026-04-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chumps', '0005_remove_era_headline_remove_specialevent_headline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='era',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
